import { describe, expect, it } from "vitest";
import {
  E_ASSISTANT_CONTENT_PARSE_FAILED,
  E_CODEISLAND_BUNDLE_MISSING,
  E_CODEISLAND_LAUNCH_BLOCKED,
  E_CODEISLAND_OS_UNSUPPORTED,
  E_LETTA_CLI_GLOBAL_SHADOWED,
  E_PROVIDER_CONNECT_FAILED,
  E_SESSION_CONVERSATION_ID_MISSING,
  E_STREAM_NO_ASSISTANT_OUTPUT,
  ERROR_CODES,
  isErrorCode,
} from "./error-codes.js";

describe("error codes", () => {
  it("exports the stable v1 observability error codes", () => {
    expect(ERROR_CODES).toMatchObject({
      CODEISLAND_OS_UNSUPPORTED: E_CODEISLAND_OS_UNSUPPORTED,
      CODEISLAND_LAUNCH_BLOCKED: E_CODEISLAND_LAUNCH_BLOCKED,
      CODEISLAND_BUNDLE_MISSING: E_CODEISLAND_BUNDLE_MISSING,
      PROVIDER_CONNECT_FAILED: E_PROVIDER_CONNECT_FAILED,
      LETTA_CLI_GLOBAL_SHADOWED: E_LETTA_CLI_GLOBAL_SHADOWED,
      SESSION_CONVERSATION_ID_MISSING: E_SESSION_CONVERSATION_ID_MISSING,
      STREAM_NO_ASSISTANT_OUTPUT: E_STREAM_NO_ASSISTANT_OUTPUT,
      ASSISTANT_CONTENT_PARSE_FAILED: E_ASSISTANT_CONTENT_PARSE_FAILED,
    });
  });

  it("validates known error code strings", () => {
    expect(isErrorCode(E_PROVIDER_CONNECT_FAILED)).toBe(true);
    expect(isErrorCode("E_NOT_A_REAL_ERROR_CODE")).toBe(false);
    expect(isErrorCode(undefined)).toBe(false);
  });
});
