export const E_CODEISLAND_OS_UNSUPPORTED = "E_CODEISLAND_OS_UNSUPPORTED";
export const E_CODEISLAND_LAUNCH_BLOCKED = "E_CODEISLAND_LAUNCH_BLOCKED";
export const E_CODEISLAND_LAUNCH_COMMAND_FAILED = "E_CODEISLAND_LAUNCH_COMMAND_FAILED";
export const E_CODEISLAND_MONITOR_RESTART_FAILED = "E_CODEISLAND_MONITOR_RESTART_FAILED";
export const E_CODEISLAND_BUNDLE_MISSING = "E_CODEISLAND_BUNDLE_MISSING";
export const E_PROVIDER_CONNECT_FAILED = "E_PROVIDER_CONNECT_FAILED";
export const E_LETTA_CLI_GLOBAL_SHADOWED = "E_LETTA_CLI_GLOBAL_SHADOWED";
export const E_LETTA_CLI_SPAWN_FAILED = "E_LETTA_CLI_SPAWN_FAILED";
export const E_LETTA_CLI_EXIT_NON_ZERO = "E_LETTA_CLI_EXIT_NON_ZERO";
export const E_SESSION_CONVERSATION_ID_MISSING = "E_SESSION_CONVERSATION_ID_MISSING";
export const E_HISTORY_LOAD_FAILED = "E_HISTORY_LOAD_FAILED";
export const E_PERMISSION_RESPONSE_MISSING = "E_PERMISSION_RESPONSE_MISSING";
export const E_STREAM_EMPTY_RESULT = "E_STREAM_EMPTY_RESULT";
export const E_STREAM_NO_ASSISTANT_OUTPUT = E_STREAM_EMPTY_RESULT;
export const E_SESSION_STOP_FAILED = "E_SESSION_STOP_FAILED";
export const E_SERVER_START_FAILED = "E_SERVER_START_FAILED";
export const E_SERVER_HEALTHCHECK_TIMEOUT = "E_SERVER_HEALTHCHECK_TIMEOUT";
export const E_SERVER_EXITED_EARLY = "E_SERVER_EXITED_EARLY";
export const E_SERVER_UNEXPECTED_EXIT = "E_SERVER_UNEXPECTED_EXIT";
export const E_ASSISTANT_CONTENT_PARSE_FAILED = "E_ASSISTANT_CONTENT_PARSE_FAILED";

export const ERROR_CODES = {
  CODEISLAND_OS_UNSUPPORTED: E_CODEISLAND_OS_UNSUPPORTED,
  CODEISLAND_LAUNCH_BLOCKED: E_CODEISLAND_LAUNCH_BLOCKED,
  CODEISLAND_LAUNCH_COMMAND_FAILED: E_CODEISLAND_LAUNCH_COMMAND_FAILED,
  CODEISLAND_MONITOR_RESTART_FAILED: E_CODEISLAND_MONITOR_RESTART_FAILED,
  CODEISLAND_BUNDLE_MISSING: E_CODEISLAND_BUNDLE_MISSING,
  PROVIDER_CONNECT_FAILED: E_PROVIDER_CONNECT_FAILED,
  LETTA_CLI_GLOBAL_SHADOWED: E_LETTA_CLI_GLOBAL_SHADOWED,
  LETTA_CLI_SPAWN_FAILED: E_LETTA_CLI_SPAWN_FAILED,
  LETTA_CLI_EXIT_NON_ZERO: E_LETTA_CLI_EXIT_NON_ZERO,
  SESSION_CONVERSATION_ID_MISSING: E_SESSION_CONVERSATION_ID_MISSING,
  HISTORY_LOAD_FAILED: E_HISTORY_LOAD_FAILED,
  PERMISSION_RESPONSE_MISSING: E_PERMISSION_RESPONSE_MISSING,
  STREAM_EMPTY_RESULT: E_STREAM_EMPTY_RESULT,
  STREAM_NO_ASSISTANT_OUTPUT: E_STREAM_NO_ASSISTANT_OUTPUT,
  SESSION_STOP_FAILED: E_SESSION_STOP_FAILED,
  SERVER_START_FAILED: E_SERVER_START_FAILED,
  SERVER_HEALTHCHECK_TIMEOUT: E_SERVER_HEALTHCHECK_TIMEOUT,
  SERVER_EXITED_EARLY: E_SERVER_EXITED_EARLY,
  SERVER_UNEXPECTED_EXIT: E_SERVER_UNEXPECTED_EXIT,
  ASSISTANT_CONTENT_PARSE_FAILED: E_ASSISTANT_CONTENT_PARSE_FAILED,
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

const ERROR_CODE_VALUES = new Set<ErrorCode>(Object.values(ERROR_CODES));

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === "string" && ERROR_CODE_VALUES.has(value as ErrorCode);
}
