import { describe, expect, it } from "vitest";
import {
  E_HISTORY_LOAD_FAILED,
  E_ASSISTANT_CONTENT_PARSE_FAILED,
  E_CODEISLAND_BUNDLE_MISSING,
  E_CODEISLAND_LAUNCH_BLOCKED,
  E_CODEISLAND_LAUNCH_COMMAND_FAILED,
  E_CODEISLAND_MONITOR_RESTART_FAILED,
  E_CODEISLAND_OS_UNSUPPORTED,
  E_LETTA_CLI_GLOBAL_SHADOWED,
  E_LETTA_CLI_EXIT_NON_ZERO,
  E_LETTA_CLI_SPAWN_FAILED,
  E_PERMISSION_RESPONSE_MISSING,
  E_PROVIDER_CONNECT_FAILED,
  E_SESSION_CONVERSATION_ID_MISSING,
  E_SESSION_STOP_FAILED,
  E_SERVER_EXITED_EARLY,
  E_SERVER_HEALTHCHECK_TIMEOUT,
  E_SERVER_START_FAILED,
  E_SERVER_UNEXPECTED_EXIT,
  E_STREAM_EMPTY_RESULT,
  E_STREAM_NO_ASSISTANT_OUTPUT,
  ERROR_CODES,
  isErrorCode,
} from "./error-codes.js";

describe("error codes", () => {
  it("exports the stable v1 observability error codes", () => {
    expect(ERROR_CODES).toMatchObject({
      CODEISLAND_OS_UNSUPPORTED: E_CODEISLAND_OS_UNSUPPORTED,
      CODEISLAND_LAUNCH_BLOCKED: E_CODEISLAND_LAUNCH_BLOCKED,
      CODEISLAND_LAUNCH_COMMAND_FAILED: E_CODEISLAND_LAUNCH_COMMAND_FAILED,
      CODEISLAND_MONITOR_RESTART_FAILED: E_CODEISLAND_MONITOR_RESTART_FAILED,
      CODEISLAND_BUNDLE_MISSING: E_CODEISLAND_BUNDLE_MISSING,
      PROVIDER_CONNECT_FAILED: E_PROVIDER_CONNECT_FAILED,
      LETTA_CLI_GLOBAL_SHADOWED: E_LETTA_CLI_GLOBAL_SHADOWED,
      LETTA_CLI_SPAWN_FAILED: E_LETTA_CLI_SPAWN_FAILED,
      LETTA_CLI_EXIT_NON_ZERO: E_LETTA_CLI_EXIT_NON_ZERO,
      SESSION_CONVERSATION_ID_MISSING: E_SESSION_CONVERSATION_ID_MISSING,
      HISTORY_LOAD_FAILED: E_HISTORY_LOAD_FAILED,
      PERMISSION_RESPONSE_MISSING: E_PERMISSION_RESPONSE_MISSING,
      STREAM_EMPTY_RESULT: E_STREAM_EMPTY_RESULT,
      STREAM_NO_ASSISTANT_OUTPUT: E_STREAM_NO_ASSISTANT_OUTPUT,
      SESSION_STOP_FAILED: E_SESSION_STOP_FAILED,
      SERVER_START_FAILED: E_SERVER_START_FAILED,
      SERVER_HEALTHCHECK_TIMEOUT: E_SERVER_HEALTHCHECK_TIMEOUT,
      SERVER_EXITED_EARLY: E_SERVER_EXITED_EARLY,
      SERVER_UNEXPECTED_EXIT: E_SERVER_UNEXPECTED_EXIT,
      ASSISTANT_CONTENT_PARSE_FAILED: E_ASSISTANT_CONTENT_PARSE_FAILED,
    });
  });

  it("validates known error code strings", () => {
    expect(isErrorCode(E_PROVIDER_CONNECT_FAILED)).toBe(true);
    expect(isErrorCode("E_NOT_A_REAL_ERROR_CODE")).toBe(false);
    expect(isErrorCode(undefined)).toBe(false);
  });
});
