export const E_CODEISLAND_OS_UNSUPPORTED = "E_CODEISLAND_OS_UNSUPPORTED";
export const E_CODEISLAND_LAUNCH_BLOCKED = "E_CODEISLAND_LAUNCH_BLOCKED";
export const E_CODEISLAND_BUNDLE_MISSING = "E_CODEISLAND_BUNDLE_MISSING";
export const E_PROVIDER_CONNECT_FAILED = "E_PROVIDER_CONNECT_FAILED";
export const E_LETTA_CLI_GLOBAL_SHADOWED = "E_LETTA_CLI_GLOBAL_SHADOWED";
export const E_SESSION_CONVERSATION_ID_MISSING = "E_SESSION_CONVERSATION_ID_MISSING";
export const E_STREAM_NO_ASSISTANT_OUTPUT = "E_STREAM_NO_ASSISTANT_OUTPUT";
export const E_ASSISTANT_CONTENT_PARSE_FAILED = "E_ASSISTANT_CONTENT_PARSE_FAILED";

export const ERROR_CODES = {
  CODEISLAND_OS_UNSUPPORTED: E_CODEISLAND_OS_UNSUPPORTED,
  CODEISLAND_LAUNCH_BLOCKED: E_CODEISLAND_LAUNCH_BLOCKED,
  CODEISLAND_BUNDLE_MISSING: E_CODEISLAND_BUNDLE_MISSING,
  PROVIDER_CONNECT_FAILED: E_PROVIDER_CONNECT_FAILED,
  LETTA_CLI_GLOBAL_SHADOWED: E_LETTA_CLI_GLOBAL_SHADOWED,
  SESSION_CONVERSATION_ID_MISSING: E_SESSION_CONVERSATION_ID_MISSING,
  STREAM_NO_ASSISTANT_OUTPUT: E_STREAM_NO_ASSISTANT_OUTPUT,
  ASSISTANT_CONTENT_PARSE_FAILED: E_ASSISTANT_CONTENT_PARSE_FAILED,
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

const ERROR_CODE_VALUES = new Set<ErrorCode>(Object.values(ERROR_CODES));

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === "string" && ERROR_CODE_VALUES.has(value as ErrorCode);
}
